name: dog
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1
repository: https://github.com/robertohuertasm/generic_bloc_provider

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  http: ^0.13.3


  cupertino_icons: ^1.0.2
  auto_route: ^7.8.4
  generic_bloc_provider: ^2.1.1
  animate_do: ^3.3.3
  flutter_svg: ^2.0.9
  hexcolor: ^3.0.1
  sliding_up_panel: ^2.0.0+1



dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.3.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpeg 